name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: deploy to server
      run: |
        ls
        dirs

    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        port: ${{ secrets.PORT }}
        pass: ${{ secrets.PASSWORD }}
        scp: |
          ./* => /root/html
        last_ssh: |
          neofetch
